# Import libraries

In [2]:
import numpy as np
import pandas as pd
import itertools

In [3]:
import tensorflow as tf
from tensorflow import keras
import tensorflow.keras.layers as tfl
from tensorflow.keras import callbacks

#--------------- If you have an error about gpu or cuda delete these two lines ------------------

physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

#----------------------------------------------------------------------------------------------------

2022-05-24 10:47:17.659132: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-24 10:47:17.688432: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-24 10:47:17.688588: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero

In [4]:
from sklearn.model_selection import train_test_split

Import the data

In [5]:
data = pd.read_csv("./final300pt.csv")# import 300 points files
data = data.iloc[:, 1:] # to remove id column

In [6]:
data

,0,1,2,3,4,5,6,7,8,9,...,892,893,894,895,896,897,898,899,angles,classes
0,1.298828,0.087891,0.529297,1.369141,0.242188,0.677734,1.365234,0.087891,0.324219,1.369141,...,0.433594,0.013672,1.339844,0.000000,0.234375,1.078125,0.115234,-1.472656,315.0,0.0
1,1.265625,-0.000000,-0.039062,1.263672,-0.000000,-0.058594,1.232422,0.039062,0.283203,1.263672,...,0.000000,0.449219,0.958984,0.193359,-0.328125,0.724609,-0.046875,0.185547,90.0,0.0
2,1.304688,-0.082031,-0.128906,1.287109,-0.123047,-0.230469,1.544922,-0.048828,0.041016,1.304688,...,-0.080078,-0.019531,1.250000,-0.119141,-0.152344,2.462891,-0.156250,-0.281250,270.0,0.0
3,1.287109,-0.097656,0.851562,1.468750,-0.097656,0.472656,1.621094,-0.000000,0.253906,1.640625,...,0.705078,-0.281250,1.695312,0.292969,1.593750,1.640625,0.433594,-0.363281,0.0,0.0
4,1.322266,0.169922,0.269531,1.337891,0.212891,0.105469,1.423828,-0.046875,0.468750,1.337891,...,0.628906,-0.205078,1.453125,-0.046875,0.367188,0.044922,0.187500,-1.488281,45.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25195,1.459542,-0.006417,0.045759,0.718750,-0.410156,1.019531,0.217773,-0.081055,-1.004883,0.455078,...,0.369141,0.990234,0.417969,-0.386719,0.970703,1.031250,0.000000,0.046875,0.0,20.0
25196,1.410156,-0.318359,0.148438,1.184570,0.076172,-0.277344,0.455078,-0.058594,0.816406,0.617188,...,0.000000,-0.171875,1.303711,-0.041016,0.145508,1.369141,0.263672,-0.183594,45.0,20.0
25197,1.714844,0.000000,-0.255859,0.820312,0.351562,1.085938,1.400391,0.132812,0.020182,0.550781,...,0.126953,0.255859,1.595703,0.050781,0.376953,1.386719,0.175781,0.152344,225.0,20.0
25198,1.388672,-0.220703,0.001953,0.332031,0.220703,1.349609,0.716797,-0.263672,-1.181641,1.292969,...,-0.212891,0.281250,1.302734,-0.339844,0.189453,1.318359,-0.255859,0.216797,135.0,20.0
25199,1.201172,0.636719,0.015625,1.488281,-0.242188,0.348633,0.587891,0.541016,1.748047,0.550781,...,0.367188,-0.011719,1.515625,0.144531,0.273438,1.416016,-0.273438,0.173828,180.0,20.0

Get X and y

In [7]:
X = data.iloc[:, :900]

In [8]:
y = data.iloc[:, 900: ]

In [9]:
X

,0,1,2,3,4,5,6,7,8,9,...,890,891,892,893,894,895,896,897,898,899
0,1.298828,0.087891,0.529297,1.369141,0.242188,0.677734,1.365234,0.087891,0.324219,1.369141,...,-1.755859,1.679688,0.433594,0.013672,1.339844,0.000000,0.234375,1.078125,0.115234,-1.472656
1,1.265625,-0.000000,-0.039062,1.263672,-0.000000,-0.058594,1.232422,0.039062,0.283203,1.263672,...,0.259766,1.382812,0.000000,0.449219,0.958984,0.193359,-0.328125,0.724609,-0.046875,0.185547
2,1.304688,-0.082031,-0.128906,1.287109,-0.123047,-0.230469,1.544922,-0.048828,0.041016,1.304688,...,0.064453,1.263672,-0.080078,-0.019531,1.250000,-0.119141,-0.152344,2.462891,-0.156250,-0.281250
3,1.287109,-0.097656,0.851562,1.468750,-0.097656,0.472656,1.621094,-0.000000,0.253906,1.640625,...,-0.171875,1.560547,0.705078,-0.281250,1.695312,0.292969,1.593750,1.640625,0.433594,-0.363281
4,1.322266,0.169922,0.269531,1.337891,0.212891,0.105469,1.423828,-0.046875,0.468750,1.337891,...,-0.085938,1.398438,0.628906,-0.205078,1.453125,-0.046875,0.367188,0.044922,0.187500,-1.488281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25195,1.459542,-0.006417,0.045759,0.718750,-0.410156,1.019531,0.217773,-0.081055,-1.004883,0.455078,...,-0.007812,0.777344,0.369141,0.990234,0.417969,-0.386719,0.970703,1.031250,0.000000,0.046875
25196,1.410156,-0.318359,0.148438,1.184570,0.076172,-0.277344,0.455078,-0.058594,0.816406,0.617188,...,0.832031,2.525391,0.000000,-0.171875,1.303711,-0.041016,0.145508,1.369141,0.263672,-0.183594
25197,1.714844,0.000000,-0.255859,0.820312,0.351562,1.085938,1.400391,0.132812,0.020182,0.550781,...,0.052734,1.329102,0.126953,0.255859,1.595703,0.050781,0.376953,1.386719,0.175781,0.152344
25198,1.388672,-0.220703,0.001953,0.332031,0.220703,1.349609,0.716797,-0.263672,-1.181641,1.292969,...,0.164062,1.312500,-0.212891,0.281250,1.302734,-0.339844,0.189453,1.318359,-0.255859,0.216797
25199,1.201172,0.636719,0.015625,1.488281,-0.242188,0.348633,0.587891,0.541016,1.748047,0.550781,...,0.027344,1.113281,0.367188,-0.011719,1.515625,0.144531,0.273438,1.416016,-0.273438,0.173828

In [10]:
y

       angles  classes
0       315.0      0.0
1        90.0      0.0
2       270.0      0.0
3         0.0      0.0
4        45.0      0.0
...       ...      ...
25195     0.0     20.0
25196    45.0     20.0
25197   225.0     20.0
25198   135.0     20.0
25199   180.0     20.0

[25200 rows x 2 columns]

We will split the data into test 20% and train 80%. We will use random seed of 10 for reproducibility

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [12]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,890,891,892,893,894,895,896,897,898,899
12735,1.439453,-0.187500,0.375000,1.478516,-0.140625,0.207031,1.406250,-0.234375,0.468750,1.394531,...,0.257812,1.478516,0.000000,0.251953,1.437500,0.000000,0.212891,1.580078,0.000000,0.441406
268,0.830078,0.105469,0.115234,1.437500,0.091797,0.187500,1.052734,-0.439453,0.271484,0.660156,...,0.025391,1.445312,0.136719,0.058594,1.427734,0.136719,0.238281,1.447266,0.136719,0.031250
13189,1.345703,0.169922,-0.101562,1.619141,-0.154297,0.218750,1.328125,0.169922,-0.234375,1.628906,...,-0.322266,1.447266,0.091797,0.107422,1.414062,0.044922,0.328125,1.404297,0.580078,-0.294922
4006,1.347656,-0.169922,0.058594,1.345703,-0.169922,-0.093750,0.751953,0.255859,1.103516,1.345703,...,-0.603516,1.398438,-0.087891,-0.125000,1.234375,-0.287109,0.341797,1.344727,-0.169922,0.101888
7897,1.433594,-0.000000,0.240234,1.441406,-0.000000,0.183594,1.425781,-0.000000,0.279297,1.445312,...,0.281250,1.375000,-0.044922,0.466797,0.275391,-0.451172,-1.201172,1.359375,0.000000,-0.009766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9372,1.388672,0.132812,0.181641,1.402344,0.087891,-0.066406,1.394531,0.175781,0.000000,1.396484,...,0.480469,1.332031,-0.212891,0.164062,1.486328,0.000000,0.199219,1.021484,-0.167969,0.298828
7291,1.496094,-0.000000,-0.117188,1.457031,-0.000000,-0.359375,1.484375,-0.000000,-0.220703,1.482422,...,-0.125000,1.466797,-0.046875,-0.308594,1.480469,-0.000000,-0.244141,1.439453,-0.093750,-0.408203
17728,1.394531,0.175781,0.037109,1.394531,0.132812,0.134766,1.382812,0.175781,0.183594,1.398438,...,0.148438,1.349609,0.308594,-0.244141,1.430664,0.091797,0.241699,1.443359,0.091797,0.143973
7293,1.722656,-0.162109,-0.111328,1.400391,0.132812,0.013672,1.703125,-0.216797,-0.240234,1.396484,...,-0.153320,1.711263,-0.143229,-0.071615,1.314453,0.169922,-0.300781,1.701172,0.326172,-0.085938
17673,1.271484,-0.000000,0.328125,1.302734,-0.000000,0.164062,1.207031,-0.000000,0.378906,1.244141,...,0.080078,1.542969,-0.199219,0.345703,1.542969,-0.359375,0.423828,1.345703,-0.085938,0.179688

In [14]:
y_test

       angles  classes
22710   135.0     10.0
15287   180.0      2.0
16397   225.0     15.0
500      45.0      6.0
5944    315.0     11.0
...       ...      ...
12423   180.0      8.0
22260    45.0      5.0
1551    180.0     19.0
13565   225.0      1.0
17066   270.0      3.0

[5040 rows x 2 columns]

In [15]:
X_train.shape

(20160, 900)

In [18]:
X_test.shape

(5040, 900)

In [19]:
y_test

       angles  classes
22710   135.0     10.0
15287   180.0      2.0
16397   225.0     15.0
500      45.0      6.0
5944    315.0     11.0
...       ...      ...
12423   180.0      8.0
22260    45.0      5.0
1551    180.0     19.0
13565   225.0      1.0
17066   270.0      3.0

[5040 rows x 2 columns]

Save test set

In [20]:
data_test = pd.DataFrame(X_test)
data_test["angles"] = y_test["angles"]
data_test["gestures"] = y_test["classes"]

In [21]:
data_test

,0,1,2,3,4,5,6,7,8,9,...,892,893,894,895,896,897,898,899,angles,gestures
22710,1.273438,-0.255859,0.400391,1.316406,-0.255859,0.222656,1.271484,-0.255859,0.410156,1.312500,...,-0.266602,0.542969,1.321533,-0.260498,0.310303,1.395410,-0.212988,0.128516,135.0,10.0
15287,1.494141,-0.046875,0.128906,1.410156,0.144531,0.621094,1.445312,-0.091797,0.130859,1.433594,...,-0.046875,0.467773,1.546875,0.410156,0.361328,1.517578,0.460938,0.417969,180.0,2.0
16397,1.302734,0.220703,0.480469,1.500000,0.046875,-0.035156,1.361328,0.220703,0.279297,1.478516,...,0.263672,-0.013672,1.539062,-0.048828,0.140625,1.478516,0.140625,-0.208984,225.0,15.0
500,1.449219,0.091797,0.035156,0.458984,-0.220703,-1.056641,1.089844,-0.175781,0.218750,1.914062,...,0.091797,0.271484,1.412109,0.318359,0.121094,1.404297,0.087891,-0.015625,45.0,6.0
5944,1.453125,-0.044922,0.017578,1.390625,-0.000000,0.207031,1.404297,-0.000000,0.080078,1.378906,...,0.097656,0.580078,1.342448,0.014974,0.417318,1.011719,0.615234,0.757812,315.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12423,1.591797,-0.000000,0.064453,1.580078,-0.099609,-0.183594,1.632812,0.050781,0.148438,1.638672,...,-0.099609,-0.101562,1.492188,0.000000,0.154297,1.724609,0.162109,-0.105469,180.0,8.0
22260,1.382812,-0.226562,0.386719,0.482422,0.000000,-1.119141,1.310547,-0.041016,-0.048828,2.529297,...,0.000000,0.238281,1.417969,-0.328125,0.363281,1.306641,0.000000,0.123047,45.0,5.0
1551,1.388672,0.181641,0.384766,1.439453,0.136719,0.148438,1.542969,-0.097656,-0.035156,1.406250,...,-0.242188,0.361328,1.449219,0.044922,0.103516,1.486328,0.187500,0.060547,180.0,19.0
13565,1.337891,0.169922,0.175781,1.351562,0.126953,-0.062500,1.636719,-0.103516,-0.029297,1.341797,...,0.343750,0.087891,1.583984,0.000000,-0.173828,1.631836,-0.154297,-0.080078,225.0,1.0
17066,1.382812,-0.000000,-0.251953,1.404297,-0.000000,-0.064453,1.378906,-0.000000,-0.277344,1.400391,...,-0.020419,-0.403853,1.718099,0.000000,0.028646,1.594922,0.000000,0.237891,270.0,3.0

In [22]:
data_test.to_pickle("./test.pkl")

Augmentation of train set

rotation function

In [23]:
def Rotate_xy(angle_x, angle_y):
    
    anglex_rad = np.deg2rad(angle_x)
    
    cos = np.cos(anglex_rad)
    sin = np.sin(anglex_rad)

    Rx  =  np.array([[1,   0,   0 ],
                     [0, cos, -sin],
                     [0, sin,  cos]]) 



    angley_rad = np.deg2rad(angle_y)

    cos = np.cos(angley_rad)
    sin = np.sin(angley_rad)

    Ry  =  np.array([[cos,  0, sin],
                     [0  ,  1,   0],
                     [-sin, 0, cos]]) 

    return np.dot(Rx, Ry)

In [24]:
X_train = X_train.to_numpy()

In [25]:
y_train = y_train.to_numpy()

In [26]:
X_train.shape

(20160, 900)

In [27]:
y_train.shape

(20160, 2)

In [28]:
data_augmented = np.zeros((20160*9, 902))

In [29]:
data_augmented

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Augmentation

In [30]:
for index in range(len(X_train)):

    sample_x = X_train[index, :].reshape((300, 3)); sample_y = y_train[index, :]
    
    for id, angles in enumerate(list(itertools.product([-15, 0, 15], [-15, 0, 15]))):
        
        rotated = np.dot(sample_x, Rotate_xy(angles[0], angles[1]))
        data_augmented[index*9+id, :] = np.hstack((rotated.reshape((900,)), sample_y))

In [31]:
data_augmented.shape

(181440, 902)

Save training set

In [35]:
data_augmented = pd.DataFrame(data_augmented)

In [37]:
data_augmented.rename(columns = {900:'angles', 901:"gestures"}, inplace = True)

In [38]:
data_augmented

,0,1,2,3,4,5,6,7,8,9,...,892,893,894,895,896,897,898,899,angles,gestures
0,1.471595,-0.278168,-0.069553,1.470474,-0.189417,-0.224661,1.459821,-0.347710,0.014792,1.394405,...,-0.065210,-0.147593,1.441741,-0.055100,-0.173423,1.636590,-0.114244,0.002883,180.0,12.0
1,1.439453,-0.278168,0.313694,1.478516,-0.189417,0.163580,1.406250,-0.347710,0.392117,1.394531,...,-0.065210,0.243368,1.437500,-0.055100,0.205637,1.580078,-0.114244,0.426366,180.0,12.0
2,1.309215,-0.278168,0.675563,1.385799,-0.189417,0.540675,1.256846,-0.347710,0.742720,1.299622,...,-0.065210,0.617743,1.335296,-0.055100,0.570682,1.415887,-0.114244,0.820792,180.0,12.0
3,1.487462,-0.187500,-0.010336,1.481720,-0.140625,-0.182691,1.479655,-0.234375,0.088813,1.389982,...,0.000000,-0.139300,1.443619,0.000000,-0.166416,1.640483,0.000000,0.017411,180.0,12.0
4,1.439453,-0.187500,0.375000,1.478516,-0.140625,0.207031,1.406250,-0.234375,0.468750,1.394531,...,0.000000,0.251953,1.437500,0.000000,0.212891,1.580078,0.000000,0.441406,180.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181435,1.271484,0.000000,0.328125,1.302734,0.000000,0.164062,1.207031,0.000000,0.378906,1.244141,...,-0.199219,0.345703,1.542969,-0.359375,0.423828,1.345703,-0.085938,0.179688,90.0,10.0
181436,1.143235,0.000000,0.646029,1.215882,0.000000,0.495645,1.067835,0.000000,0.678398,1.140581,...,-0.199219,0.733273,1.380699,-0.359375,0.808736,1.253343,-0.085938,0.521858,90.0,10.0
181437,1.310191,0.084925,-0.022940,1.299360,0.042462,-0.184100,1.260629,0.098068,0.041122,1.260830,...,-0.102956,-0.027000,1.620424,-0.237435,0.085931,1.350528,-0.036503,-0.159159,90.0,10.0
181438,1.271484,0.084925,0.316944,1.302734,0.042462,0.158472,1.207031,0.098068,0.365995,1.244141,...,-0.102956,0.385485,1.542969,-0.237435,0.502400,1.345703,-0.036503,0.195807,90.0,10.0
181439,1.146128,0.084925,0.635229,1.217329,0.042462,0.490245,1.071176,0.098068,0.665927,1.142666,...,-0.102956,0.771700,1.360363,-0.237435,0.884630,1.249171,-0.036503,0.537429,90.0,10.0

In [40]:
data_augmented.iloc[:, -2].value_counts()

270.0    23022
90.0     22896
180.0    22788
135.0    22617
225.0    22608
0.0      22581
315.0    22473
45.0     22455
Name: angles, dtype: int64

In [41]:
data_augmented.to_pickle("./train.pkl")